### ISSUE TITLE
必须使用3.2版本吗，用最新的3.4会不会有问题呢

### ISSUE THREAD

**Issue by murazi** [DowneyL/discuz-wechat-miniprogram#2]
RT

**Comment by august6th** [comment]
有人测试反馈说 3.4 是可以使用的，具体情况还需要您自己实践。

**Comment by murazi** [comment]
好的，谢谢了


以后还会对这个代码做更新吗？


------------------
              Arens SUN      
               Email:                                arens@qq.com                                
                            Gmail:                      Murazisun@Gmail.com                   
                           Mobile:                                                                                                                           170 7942 8219                                                                       (洛阳)               


 




------------------ 原始邮件 ------------------
发件人: "heng lee"<notifications@github.com>;
发送时间: 2018年4月23日(星期一) 下午2:39
收件人: "DowneyL/discuz-wechat-miniprogram"<discuz-wechat-miniprogram@noreply.github.com>;
抄送: "arens"<arens@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [DowneyL/discuz-wechat-miniprogram] 必须使用3.2版本吗，用最新的3.4会不会有问题呢 (#2)




有人测试反馈说 3.4 是可以使用的，具体情况还需要您自己实践。

**Comment by youngjuning** [comment]
支持开源，给个打赏的呗，我给你打赏

**Comment by august6th** [comment]
@murazi 暂时不会更新了，个人时间有限，不好意思

@youngjuning 谢谢您的支持，不过项目代码还很糙，不值得被打赏，哈哈哈
